import type { ScanResult, UxIssue } from "../types";

function section(title: string, issues: UxIssue[]): string {
  if (issues.length === 0) return "";
  const out: string[] = [];
  out.push(`### ${title}`);
  out.push("");
  for (const i of issues) {
    const loc = i.line ? `:${i.line}` : "";
    out.push(`- **\`${i.file}${loc}\`** — ${i.message}`);
    out.push(`  - _Fix:_ ${i.suggestion}`);
  }
  out.push("");
  return out.join("\n");
}

export function renderMarkdown(result: ScanResult): string {
  const out: string[] = [];
  out.push(`## UX Completeness Report`);
  out.push("");
  out.push(`**Score:** ${result.score}/100`);
  out.push("");
  out.push(
    `Scanned **${result.filesScanned}** files. Found **${result.issues.length}** issue${result.issues.length === 1 ? "" : "s"}.`,
  );
  out.push("");

  if (result.issues.length === 0) {
    out.push("> ✅ No UX completeness issues found. Ship it!");
    out.push("");
    return out.join("\n");
  }

  const errors = result.issues.filter((i) => i.severity === "error");
  const warns = result.issues.filter((i) => i.severity === "warn");
  const infos = result.issues.filter((i) => i.severity === "info");

  out.push(section("🚨 Must fix", errors));
  out.push(section("⚠️ Should fix", warns));
  out.push(section("ℹ️ Nice to have", infos));

  out.push("---");
  out.push("");
  out.push(
    `_Generated by [uxaudit](https://github.com/x1n-Q/uxaudit) — the missing-state checker for modern web apps._`,
  );
  out.push("");
  return out.join("\n");
}
